# basic options
title: My Blog
author: jguha
email: your-email@domain.com
description: A wonderful blog
twitter_username: jguha
github_username:  jguha12

# Build settings
markdown: kramdown
theme: minima
